### ISSUE TITLE
KeyError: 'XX'

### ISSUE THREAD

**Issue by Joao-Maria-Janeiro** [adrianeboyd/errant#1]
Hi,

I get this error when using your German ERRANT.

I am using (as per your recommendation):
- nltk==3.6.7
- spacy==2.0.11
- treetaggerwrapper==2.2.4

But I get the error: KeyError: 'XX'

Which I think is related to the fact that you have (https://github.com/adrianeboyd/errant/blob/798103ebe2a4563e518c06314feae6cbcbf8bacf/scripts/toolbox.py#L130):
for tok in sent:
	if tok.tag_ == "":
		tok.tag_ = "XX"

But then in your german mappings (https://github.com/adrianeboyd/errant/blob/german/resources/de-stts_map) you don't account for this tag, neither in the cat_rules_de. It seems that you apply this tag but then don't handle it in the code.

Maybe this could be fixed by simply switching the "XX" to "X" or "XY", which are both handled?

**Comment by adrianeboyd** [comment]
Sorry, this code is no longer maintained. Maybe the model versions aren't identical even though the software versions are? (It does look like a bug, but I'm not sure how you end up with an empty tag in the first place?)

If you want to work with the German extensions, it might be worth porting the changes in this fork to the newest upstream version of errant, which may have more bug fixes and can run with newer versions of the dependencies?
